#-------------------------------------------------
#
# Project created by QtCreator 2014-04-10T02:36:03
#
#-------------------------------------------------

QT       -= gui

TARGET = IEC61850
TEMPLATE = lib

DEFINES += IEC61850_LIBRARY

INCLUDEPATH += Part7 \
    Part7/LogicalNodes \
    Part7/LogicalNodes/DomainLNs \
    Part7/LogicalNodes/DomainLNs/LNGroupF \
    Part7/LogicalNodes/DomainLNs/DomainLN \
    Part7/LogicalNodes/DomainLNs/LNGroupA \
    Part7/LogicalNodes/DomainLNs/LNGroupT \
    Part7/LogicalNodes/DomainLNs/LNGroupY \
    Part7/LogicalNodes/DomainLNs/LNGroupX \
    Part7/LogicalNodes/DomainLNs/LNGroupM \
    Part7/LogicalNodes/LNGroupL \
    Part7/CommonDataClasses \
    Part7/CommonDataClasses/FCDAs \
    Part7/CommonDataClasses/CDCs \
    Part7/CommonDataClasses/CDCs/CDCAnalogueInfo \
    Part7/CommonDataClasses/CDCs/CDCStatusCtl \
    Part7/CommonDataClasses/CDCs/CDCAnalogueSet \
    Part7/CommonDataClasses/CDCs/CDCAnalogueCtl \
    Part7/CommonDataClasses/CDCs/CDCStatusSet \
    Part7/CommonDataClasses/CDCs/CDCBase \
    Part7/CommonDataClasses/CDCs/CDCStatusInfo \
    Part7/CommonDataClasses/CDCs/CDCDescription \
    Part7/ACSI \
    Part7/ACSI/CoreTypes \
    Part7/ACSI/CoreEnums \
    Part7/ACSI/CoreEnums/CommonDAEnums \
    Part7/ACSI/MetaModel \
    Part7/ACSI/AcsiTypes \
    Part7/ACSI/AcsiTypes/ObjectReferences \
    Part7/ACSI/AcsiTypes/CommonAcsiTypes \
    Part7/DAs \
    Part7/DAs/CommonDAs \
    Part7/DAs/CommonAcsiDAs \
    Part7/DAs/BasicDAs


SOURCES += iec61850.cpp \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/AccessView.cpp \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/Authentication.cpp \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/IPAddress.cpp \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/MulticastAddress.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/CBReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/CDCReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/FCDAReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/FCDReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/FILEReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/LDReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/LNOwnedDSReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/LNReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/LOGReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/NonPersistentDSReference.cpp \
        Part7/ACSI/AcsiTypes/ObjectReferences/ObjectReference.cpp \
        Part7/ACSI/CoreTypes/DetailQual.cpp \
        Part7/ACSI/CoreTypes/ObjectName.cpp \
        Part7/ACSI/CoreTypes/P_BOOLEAN.cpp \
        Part7/ACSI/CoreTypes/P_FLOAT32.cpp \
        Part7/ACSI/CoreTypes/P_INT128.cpp \
        Part7/ACSI/CoreTypes/P_INT16.cpp \
        Part7/ACSI/CoreTypes/P_INT16U.cpp \
        Part7/ACSI/CoreTypes/P_INT24U.cpp \
        Part7/ACSI/CoreTypes/P_INT32.cpp \
        Part7/ACSI/CoreTypes/P_INT32U.cpp \
        Part7/ACSI/CoreTypes/P_INT8.cpp \
        Part7/ACSI/CoreTypes/P_INT8U.cpp \
        Part7/ACSI/CoreTypes/P_OCTET_STRING64.cpp \
        Part7/ACSI/CoreTypes/P_Quality.cpp \
        Part7/ACSI/CoreTypes/P_TimeStamp.cpp \
        Part7/ACSI/CoreTypes/P_UNICODE_STRING255.cpp \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING255.cpp \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING32.cpp \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING64.cpp \
        Part7/ACSI/CoreTypes/TimeQuality.cpp \
        Part7/ACSI/MetaModel/CDC.cpp \
        Part7/ACSI/MetaModel/ComposedCDC.cpp \
        Part7/ACSI/MetaModel/ComposedDA.cpp \
        Part7/ACSI/MetaModel/ConfiguredDS.cpp \
        Part7/ACSI/MetaModel/ControlBlock.cpp \
        Part7/ACSI/MetaModel/DA.cpp \
        Part7/ACSI/MetaModel/DS.cpp \
        Part7/ACSI/MetaModel/FCD.cpp \
        Part7/ACSI/MetaModel/FCDA.cpp \
        Part7/ACSI/MetaModel/FCDA_CF.cpp \
        Part7/ACSI/MetaModel/FCDA_CO.cpp \
        Part7/ACSI/MetaModel/FCDA_DC.cpp \
        Part7/ACSI/MetaModel/FCDA_EX.cpp \
        Part7/ACSI/MetaModel/FCDA_MC.cpp \
        Part7/ACSI/MetaModel/FCDA_MX.cpp \
        Part7/ACSI/MetaModel/FCDA_MX_dchg.cpp \
        Part7/ACSI/MetaModel/FCDA_MX_dchg_dupd.cpp \
        Part7/ACSI/MetaModel/FCDA_MX_qchg.cpp \
        Part7/ACSI/MetaModel/FCDA_SE.cpp \
        Part7/ACSI/MetaModel/FCDA_SG.cpp \
        Part7/ACSI/MetaModel/FCDA_SP.cpp \
        Part7/ACSI/MetaModel/FCDA_ST.cpp \
        Part7/ACSI/MetaModel/FCDA_ST_dchg.cpp \
        Part7/ACSI/MetaModel/FCDA_ST_dupd.cpp \
        Part7/ACSI/MetaModel/FCDA_ST_qchg.cpp \
        Part7/ACSI/MetaModel/FCDA_SV.cpp \
        Part7/ACSI/MetaModel/FILE.cpp \
        Part7/ACSI/MetaModel/HierarchyIEC61850Object.cpp \
        Part7/ACSI/MetaModel/IEC61850Object.cpp \
        Part7/ACSI/MetaModel/IED.cpp \
        Part7/ACSI/MetaModel/LD.cpp \
        Part7/ACSI/MetaModel/LN.cpp \
        Part7/ACSI/MetaModel/LN0.cpp \
        Part7/ACSI/MetaModel/LNDOM.cpp \
        Part7/ACSI/MetaModel/LNOwnedDS.cpp \
        Part7/ACSI/MetaModel/LNPHD.cpp \
        Part7/ACSI/MetaModel/LOG.cpp \
        Part7/ACSI/MetaModel/MCAA.cpp \
        Part7/ACSI/MetaModel/MSVCB.cpp \
        Part7/ACSI/MetaModel/NamedIEC61850Object.cpp \
        Part7/ACSI/MetaModel/NonPersistentDS.cpp \
        Part7/ACSI/MetaModel/PersistentDS.cpp \
        Part7/ACSI/MetaModel/PrimitiveCDC.cpp \
        Part7/ACSI/MetaModel/PrimitiveDA.cpp \
        Part7/ACSI/MetaModel/SERVER.cpp \
        Part7/ACSI/MetaModel/SVCB.cpp \
        Part7/ACSI/MetaModel/TPAA.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueCtl/APC.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueCtl/ControllableAnalogueInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/CMV.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/ComposedMeasurandInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/DEL.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HDEL.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HMV.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HWYE.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/MV.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/PrimitiveMeasurandInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/SAV.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/SEQ.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/WYE.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/AnalogueSettings.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/ASG.cpp \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/CURVE.cpp \
        Part7/CommonDataClasses/CDCs/CDCBase/C_ComposedCDC.cpp \
        Part7/CommonDataClasses/CDCs/CDCBase/C_PrimitiveCDC.cpp \
        Part7/CommonDataClasses/CDCs/CDCDescription/CSD.cpp \
        Part7/CommonDataClasses/CDCs/CDCDescription/DescriptionInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCDescription/DPL.cpp \
        Part7/CommonDataClasses/CDCs/CDCDescription/LPL.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/BSC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/ControllableStatusInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/DPC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_ENUM.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_FanControl.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_ModeBehaviour.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_PumpControl.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/ISC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/SPC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/SPC_transient.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACD.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACT.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACT_transient.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/BCR.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/DPS.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_AutoReclosingStatus.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_BreakerOperatingCapability.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_ENUM.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_FaultLoop.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_GeneratorState.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_HealthState.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_ModeBehaviour.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_SwitchingCapability.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_SwitchType.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SEC.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SPS.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SPS_transient.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/StatusInfo.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_CurrentReversalMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_DirectionMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_ENUM.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_FailureDetectionMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_InternalTriggerMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_LiveDeadMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_PolarizingQuantity.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RecordingMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_ResetCurve.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RestraintMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RetripMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_SchemeType.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_TriggerSource.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_TripMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_UnblockFunctionMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_WeakEndInfeedMode.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/SPG.cpp \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/StatusSettings.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_CF.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MC.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MX.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MX_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SE.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SG.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SP.cpp \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SV.cpp \
        Part7/CommonDataClasses/FCDAs/AngleReference_CF.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_CF.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_CO.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SE.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SG.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SP.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SV.cpp \
        Part7/CommonDataClasses/FCDAs/BSControl_CO.cpp \
        Part7/CommonDataClasses/FCDAs/CMVAngleReference_CF.cpp \
        Part7/CommonDataClasses/FCDAs/CtlModels_CF.cpp \
        Part7/CommonDataClasses/FCDAs/CurveChar_SE.cpp \
        Part7/CommonDataClasses/FCDAs/CurveChar_SG.cpp \
        Part7/CommonDataClasses/FCDAs/CurveChar_SP.cpp \
        Part7/CommonDataClasses/FCDAs/DirectionPhase_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/DPStatus_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/DPStatus_SV.cpp \
        Part7/CommonDataClasses/FCDAs/FaultDirection_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/FLOAT32_CF.cpp \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SE.cpp \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SG.cpp \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SP.cpp \
        Part7/CommonDataClasses/FCDAs/INT128_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/INT128_ST_dupd.cpp \
        Part7/CommonDataClasses/FCDAs/INT16U_CF.cpp \
        Part7/CommonDataClasses/FCDAs/INT16U_DC.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_CF.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_CO.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_SE.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_SG.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_SP.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/INT32_SV.cpp \
        Part7/CommonDataClasses/FCDAs/INT32U_CF.cpp \
        Part7/CommonDataClasses/FCDAs/INT32U_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/INT8_CF.cpp \
        Part7/CommonDataClasses/FCDAs/INT8_CO.cpp \
        Part7/CommonDataClasses/FCDAs/INT8U_CF.cpp \
        Part7/CommonDataClasses/FCDAs/INT8U_CO.cpp \
        Part7/CommonDataClasses/FCDAs/INT8U_ST.cpp \
        Part7/CommonDataClasses/FCDAs/MagReference_CF.cpp \
        Part7/CommonDataClasses/FCDAs/OCTET_STRING64_ST.cpp \
        Part7/CommonDataClasses/FCDAs/Originator_CO.cpp \
        Part7/CommonDataClasses/FCDAs/Originator_MC.cpp \
        Part7/CommonDataClasses/FCDAs/Originator_MX.cpp \
        Part7/CommonDataClasses/FCDAs/Originator_ST.cpp \
        Part7/CommonDataClasses/FCDAs/PhaseReference_CF.cpp \
        Part7/CommonDataClasses/FCDAs/PointArray_DC.cpp \
        Part7/CommonDataClasses/FCDAs/PulseConfig_CF.cpp \
        Part7/CommonDataClasses/FCDAs/Quality_MX_qchg.cpp \
        Part7/CommonDataClasses/FCDAs/Quality_ST_qchg.cpp \
        Part7/CommonDataClasses/FCDAs/Quality_SV.cpp \
        Part7/CommonDataClasses/FCDAs/Range_MX_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/RangeConfig_CF.cpp \
        Part7/CommonDataClasses/FCDAs/SboClasses_CF.cpp \
        Part7/CommonDataClasses/FCDAs/ScaledValueConfig_CF.cpp \
        Part7/CommonDataClasses/FCDAs/Sequence_MX.cpp \
        Part7/CommonDataClasses/FCDAs/Severity_ST.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_CF.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_CO.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_MC.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_MX.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_ST.cpp \
        Part7/CommonDataClasses/FCDAs/TimeStamp_ST_dupd.cpp \
        Part7/CommonDataClasses/FCDAs/UNICODE_STRING255_DC.cpp \
        Part7/CommonDataClasses/FCDAs/Unit_CF.cpp \
        Part7/CommonDataClasses/FCDAs/Unit_DC.cpp \
        Part7/CommonDataClasses/FCDAs/ValWithTrans_ST_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/ValWithTrans_SV.cpp \
        Part7/CommonDataClasses/FCDAs/Vector_MX.cpp \
        Part7/CommonDataClasses/FCDAs/Vector_MX_dchg.cpp \
        Part7/CommonDataClasses/FCDAs/Vector_SV.cpp \
        Part7/CommonDataClasses/FCDAs/VectorArray_MX_dchg_dupd.cpp \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING255_DC.cpp \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING255_EX.cpp \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING64_ST.cpp \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING64_SV.cpp \
        Part7/DAs/BasicDAs/BOOLEAN.cpp \
        Part7/DAs/BasicDAs/FLOAT32.cpp \
        Part7/DAs/BasicDAs/INT128.cpp \
        Part7/DAs/BasicDAs/INT16.cpp \
        Part7/DAs/BasicDAs/INT16U.cpp \
        Part7/DAs/BasicDAs/INT32.cpp \
        Part7/DAs/BasicDAs/INT32U.cpp \
        Part7/DAs/BasicDAs/INT8.cpp \
        Part7/DAs/BasicDAs/INT8U.cpp \
        Part7/DAs/BasicDAs/OCTET_STRING64.cpp \
        Part7/DAs/BasicDAs/UNICODE_STRING255.cpp \
        Part7/DAs/BasicDAs/VISIBLE_STRING255.cpp \
        Part7/DAs/BasicDAs/VISIBLE_STRING64.cpp \
        Part7/DAs/CommonAcsiDAs/TimeStamp.cpp \
        Part7/DAs/CommonDAs/AnalogueValue.cpp \
        Part7/DAs/CommonDAs/AngleReference.cpp \
        Part7/DAs/CommonDAs/BSControl.cpp \
        #Part7/DAs/CommonDAs/Class1.cpp \
        Part7/DAs/CommonDAs/CMVAngleReference.cpp \
        Part7/DAs/CommonDAs/ControlOutput.cpp \
        Part7/DAs/CommonDAs/CtlModels.cpp \
        Part7/DAs/CommonDAs/CurveChar.cpp \
        Part7/DAs/CommonDAs/DirectionPhase.cpp \
        Part7/DAs/CommonDAs/DPStatus.cpp \
        Part7/DAs/CommonDAs/FaultDirection.cpp \
        Part7/DAs/CommonDAs/MagReference.cpp \
        Part7/DAs/CommonDAs/Multiplier.cpp \
        Part7/DAs/CommonDAs/Originator.cpp \
        Part7/DAs/CommonDAs/OriginatorCategory.cpp \
        Part7/DAs/CommonDAs/PhaseReference.cpp \
        Part7/DAs/CommonDAs/Point.cpp \
        Part7/DAs/CommonDAs/PointArray.cpp \
        Part7/DAs/CommonDAs/PulseConfig.cpp \
        Part7/DAs/CommonDAs/Quality.cpp \
        Part7/DAs/CommonDAs/Range.cpp \
        Part7/DAs/CommonDAs/RangeConfig.cpp \
        Part7/DAs/CommonDAs/SboClasses.cpp \
        Part7/DAs/CommonDAs/ScaledValueConfig.cpp \
        Part7/DAs/CommonDAs/Sequence.cpp \
        Part7/DAs/CommonDAs/Severity.cpp \
        Part7/DAs/CommonDAs/SIUnits.cpp \
        Part7/DAs/CommonDAs/Unit.cpp \
        Part7/DAs/CommonDAs/ValWithTrans.cpp \
        Part7/DAs/CommonDAs/Vector.cpp \
        Part7/DAs/CommonDAs/VectorArray.cpp \
        Part7/LogicalNodes/DomainLNs/DomainLN/DomainLN.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ANCR.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ARCO.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ATCC.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupA/GroupA.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupF/FSPT.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupF/GroupF.cpp \
        #Part7/LogicalNodes/DomainLNs/LNGroupM/Class1.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/GroupM.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MDIF.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MHAI.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MHAN.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMTR.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMXN.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMXU.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MSQI.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MSTA.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupT/GroupT.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupT/TCTR.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupT/TVTR.cpp \
        #Part7/LogicalNodes/DomainLNs/LNGroupX/Class1.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupX/GroupX.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupX/XCBR.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupX/XSWI.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupY/GroupY.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YEFN.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YLTC.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YPSH.cpp \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YPTR.cpp \
        Part7/LogicalNodes/LNGroupL/LLN0.cpp \
        Part7/LogicalNodes/LNGroupL/LPHD.cpp

HEADERS += iec61850.h\
        iec61850_global.h \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/AccessView.h \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/Authentication.h \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/IPAddress.h \
        Part7/ACSI/AcsiTypes/CommonAcsiTypes/MulticastAddress.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/CBReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/CDCReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/FCDAReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/FCDReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/FILEReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/LDReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/LNOwnedDSReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/LNReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/LOGReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/NonPersistentDSReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/ObjectReference.h \
        Part7/ACSI/AcsiTypes/ObjectReferences/ServiceFcKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/AngleReferenceKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/BSControlKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/CMVAngleReferenceKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/ControlOutputKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/CtlModelsKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/CurveCharKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/DirectionPhaseKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/DPStatusKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/FaultDirectionKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/MagReferenceKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/MultiplierKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/OriginatorCategoryKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/PhaseReferenceKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/RangeKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/SboClassesKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/SequenceKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/SeverityKind.h \
        Part7/ACSI/CoreEnums/CommonDAEnums/SIUnitsKind.h \
        Part7/ACSI/CoreTypes/DetailQual.h \
        Part7/ACSI/CoreTypes/FcKind.h \
        Part7/ACSI/CoreTypes/ObjectName.h \
        Part7/ACSI/CoreTypes/P_BOOLEAN.h \
        Part7/ACSI/CoreTypes/P_FLOAT32.h \
        Part7/ACSI/CoreTypes/P_INT128.h \
        Part7/ACSI/CoreTypes/P_INT16.h \
        Part7/ACSI/CoreTypes/P_INT16U.h \
        Part7/ACSI/CoreTypes/P_INT24U.h \
        Part7/ACSI/CoreTypes/P_INT32.h \
        Part7/ACSI/CoreTypes/P_INT32U.h \
        Part7/ACSI/CoreTypes/P_INT8.h \
        Part7/ACSI/CoreTypes/P_INT8U.h \
        Part7/ACSI/CoreTypes/P_OCTET_STRING64.h \
        Part7/ACSI/CoreTypes/P_Quality.h \
        Part7/ACSI/CoreTypes/P_TimeStamp.h \
        Part7/ACSI/CoreTypes/P_UNICODE_STRING255.h \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING255.h \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING32.h \
        Part7/ACSI/CoreTypes/P_VISIBLE_STRING64.h \
        Part7/ACSI/CoreTypes/SourceKind.h \
        Part7/ACSI/CoreTypes/TimeAccuracyKind.h \
        Part7/ACSI/CoreTypes/TimeQuality.h \
        Part7/ACSI/CoreTypes/TrgOpKind.h \
        Part7/ACSI/CoreTypes/ValidityKind.h \
        Part7/ACSI/MetaModel/CDC.h \
        Part7/ACSI/MetaModel/ComposedCDC.h \
        Part7/ACSI/MetaModel/ComposedDA.h \
        Part7/ACSI/MetaModel/ConfiguredDS.h \
        Part7/ACSI/MetaModel/ControlBlock.h \
        Part7/ACSI/MetaModel/DA.h \
        Part7/ACSI/MetaModel/DS.h \
        Part7/ACSI/MetaModel/FCD.h \
        Part7/ACSI/MetaModel/FCDA.h \
        Part7/ACSI/MetaModel/FCDA_CF.h \
        Part7/ACSI/MetaModel/FCDA_CO.h \
        Part7/ACSI/MetaModel/FCDA_DC.h \
        Part7/ACSI/MetaModel/FCDA_EX.h \
        Part7/ACSI/MetaModel/FCDA_MC.h \
        Part7/ACSI/MetaModel/FCDA_MX.h \
        Part7/ACSI/MetaModel/FCDA_MX_dchg.h \
        Part7/ACSI/MetaModel/FCDA_MX_dchg_dupd.h \
        Part7/ACSI/MetaModel/FCDA_MX_qchg.h \
        Part7/ACSI/MetaModel/FCDA_SE.h \
        Part7/ACSI/MetaModel/FCDA_SG.h \
        Part7/ACSI/MetaModel/FCDA_SP.h \
        Part7/ACSI/MetaModel/FCDA_ST.h \
        Part7/ACSI/MetaModel/FCDA_ST_dchg.h \
        Part7/ACSI/MetaModel/FCDA_ST_dupd.h \
        Part7/ACSI/MetaModel/FCDA_ST_qchg.h \
        Part7/ACSI/MetaModel/FCDA_SV.h \
        Part7/ACSI/MetaModel/FILE.h \
        Part7/ACSI/MetaModel/HierarchyIEC61850Object.h \
        Part7/ACSI/MetaModel/IEC61850Object.h \
        Part7/ACSI/MetaModel/IED.h \
        Part7/ACSI/MetaModel/LD.h \
        Part7/ACSI/MetaModel/LN.h \
        Part7/ACSI/MetaModel/LN0.h \
        Part7/ACSI/MetaModel/LNDOM.h \
        Part7/ACSI/MetaModel/LNOwnedDS.h \
        Part7/ACSI/MetaModel/LNPHD.h \
        Part7/ACSI/MetaModel/LOG.h \
        Part7/ACSI/MetaModel/MCAA.h \
        Part7/ACSI/MetaModel/MSVCB.h \
        Part7/ACSI/MetaModel/NamedIEC61850Object.h \
        Part7/ACSI/MetaModel/NonPersistentDS.h \
        Part7/ACSI/MetaModel/PersistentDS.h \
        Part7/ACSI/MetaModel/PrimitiveCDC.h \
        Part7/ACSI/MetaModel/PrimitiveDA.h \
        Part7/ACSI/MetaModel/SERVER.h \
        Part7/ACSI/MetaModel/SVCB.h \
        Part7/ACSI/MetaModel/TPAA.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueCtl/APC.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueCtl/ControllableAnalogueInfo.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/CMV.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/ComposedMeasurandInfo.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/DEL.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HDEL.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HMV.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/HWYE.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/MV.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/PrimitiveMeasurandInfo.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/SAV.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/SEQ.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueInfo/WYE.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/AnalogueSettings.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/ASG.h \
        Part7/CommonDataClasses/CDCs/CDCAnalogueSet/CURVE.h \
        Part7/CommonDataClasses/CDCs/CDCBase/C_ComposedCDC.h \
        Part7/CommonDataClasses/CDCs/CDCBase/C_PrimitiveCDC.h \
        Part7/CommonDataClasses/CDCs/CDCDescription/CSD.h \
        Part7/CommonDataClasses/CDCs/CDCDescription/DescriptionInfo.h \
        Part7/CommonDataClasses/CDCs/CDCDescription/DPL.h \
        Part7/CommonDataClasses/CDCs/CDCDescription/LPL.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/BSC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/ControllableStatusInfo.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/DPC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_ENUM.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_FanControl.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_ModeBehaviour.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/INC_PumpControl.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/ISC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/SPC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusCtl/SPC_transient.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACD.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACT.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/ACT_transient.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/BCR.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/DPS.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_AutoReclosingStatus.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_BreakerOperatingCapability.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_ENUM.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_FaultLoop.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_GeneratorState.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_HealthState.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_ModeBehaviour.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_SwitchingCapability.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/INS_SwitchType.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SEC.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SPS.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/SPS_transient.h \
        Part7/CommonDataClasses/CDCs/CDCStatusInfo/StatusInfo.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_CurrentReversalMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_DirectionMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_ENUM.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_FailureDetectionMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_InternalTriggerMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_LiveDeadMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_PolarizingQuantity.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RecordingMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_ResetCurve.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RestraintMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_RetripMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_SchemeType.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_TriggerSource.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_TripMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_UnblockFunctionMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/ING_WeakEndInfeedMode.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/SPG.h \
        Part7/CommonDataClasses/CDCs/CDCStatusSet/StatusSettings.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_CF.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MC.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MX.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_MX_dchg.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SE.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SG.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SP.h \
        Part7/CommonDataClasses/FCDAs/AnalogueValue_SV.h \
        Part7/CommonDataClasses/FCDAs/AngleReference_CF.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_CF.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_CO.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SE.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SG.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SP.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/BOOLEAN_SV.h \
        Part7/CommonDataClasses/FCDAs/BSControl_CO.h \
        Part7/CommonDataClasses/FCDAs/CMVAngleReference_CF.h \
        Part7/CommonDataClasses/FCDAs/CtlModels_CF.h \
        Part7/CommonDataClasses/FCDAs/CurveChar_SE.h \
        Part7/CommonDataClasses/FCDAs/CurveChar_SG.h \
        Part7/CommonDataClasses/FCDAs/CurveChar_SP.h \
        Part7/CommonDataClasses/FCDAs/DirectionPhase_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/DPStatus_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/DPStatus_SV.h \
        Part7/CommonDataClasses/FCDAs/FaultDirection_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/FLOAT32_CF.h \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SE.h \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SG.h \
        Part7/CommonDataClasses/FCDAs/FLOAT32_SP.h \
        Part7/CommonDataClasses/FCDAs/INT128_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/INT128_ST_dupd.h \
        Part7/CommonDataClasses/FCDAs/INT16U_CF.h \
        Part7/CommonDataClasses/FCDAs/INT16U_DC.h \
        Part7/CommonDataClasses/FCDAs/INT32_CF.h \
        Part7/CommonDataClasses/FCDAs/INT32_CO.h \
        Part7/CommonDataClasses/FCDAs/INT32_SE.h \
        Part7/CommonDataClasses/FCDAs/INT32_SG.h \
        Part7/CommonDataClasses/FCDAs/INT32_SP.h \
        Part7/CommonDataClasses/FCDAs/INT32_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/INT32_SV.h \
        Part7/CommonDataClasses/FCDAs/INT32U_CF.h \
        Part7/CommonDataClasses/FCDAs/INT32U_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/INT8_CF.h \
        Part7/CommonDataClasses/FCDAs/INT8_CO.h \
        Part7/CommonDataClasses/FCDAs/INT8U_CF.h \
        Part7/CommonDataClasses/FCDAs/INT8U_CO.h \
        Part7/CommonDataClasses/FCDAs/INT8U_ST.h \
        Part7/CommonDataClasses/FCDAs/MagReference_CF.h \
        Part7/CommonDataClasses/FCDAs/OCTET_STRING64_ST.h \
        Part7/CommonDataClasses/FCDAs/Originator_CO.h \
        Part7/CommonDataClasses/FCDAs/Originator_MC.h \
        Part7/CommonDataClasses/FCDAs/Originator_MX.h \
        Part7/CommonDataClasses/FCDAs/Originator_ST.h \
        Part7/CommonDataClasses/FCDAs/PhaseReference_CF.h \
        Part7/CommonDataClasses/FCDAs/PointArray_DC.h \
        Part7/CommonDataClasses/FCDAs/PulseConfig_CF.h \
        Part7/CommonDataClasses/FCDAs/Quality_MX_qchg.h \
        Part7/CommonDataClasses/FCDAs/Quality_ST_qchg.h \
        Part7/CommonDataClasses/FCDAs/Quality_SV.h \
        Part7/CommonDataClasses/FCDAs/Range_MX_dchg.h \
        Part7/CommonDataClasses/FCDAs/RangeConfig_CF.h \
        Part7/CommonDataClasses/FCDAs/SboClasses_CF.h \
        Part7/CommonDataClasses/FCDAs/ScaledValueConfig_CF.h \
        Part7/CommonDataClasses/FCDAs/Sequence_MX.h \
        Part7/CommonDataClasses/FCDAs/Severity_ST.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_CF.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_CO.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_MC.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_MX.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_ST.h \
        Part7/CommonDataClasses/FCDAs/TimeStamp_ST_dupd.h \
        Part7/CommonDataClasses/FCDAs/UNICODE_STRING255_DC.h \
        Part7/CommonDataClasses/FCDAs/Unit_CF.h \
        Part7/CommonDataClasses/FCDAs/Unit_DC.h \
        Part7/CommonDataClasses/FCDAs/ValWithTrans_ST_dchg.h \
        Part7/CommonDataClasses/FCDAs/ValWithTrans_SV.h \
        Part7/CommonDataClasses/FCDAs/Vector_MX.h \
        Part7/CommonDataClasses/FCDAs/Vector_MX_dchg.h \
        Part7/CommonDataClasses/FCDAs/Vector_SV.h \
        Part7/CommonDataClasses/FCDAs/VectorArray_MX_dchg_dupd.h \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING255_DC.h \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING255_EX.h \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING64_ST.h \
        Part7/CommonDataClasses/FCDAs/VISIBLE_STRING64_SV.h \
        Part7/DAs/BasicDAs/BOOLEAN.h \
        Part7/DAs/BasicDAs/FLOAT32.h \
        Part7/DAs/BasicDAs/INT128.h \
        Part7/DAs/BasicDAs/INT16.h \
        Part7/DAs/BasicDAs/INT16U.h \
        Part7/DAs/BasicDAs/INT32.h \
        Part7/DAs/BasicDAs/INT32U.h \
        Part7/DAs/BasicDAs/INT8.h \
        Part7/DAs/BasicDAs/INT8U.h \
        Part7/DAs/BasicDAs/OCTET_STRING64.h \
        Part7/DAs/BasicDAs/UNICODE_STRING255.h \
        Part7/DAs/BasicDAs/VISIBLE_STRING255.h \
        Part7/DAs/BasicDAs/VISIBLE_STRING64.h \
        Part7/DAs/CommonAcsiDAs/TimeStamp.h \
        Part7/DAs/CommonDAs/AnalogueValue.h \
        Part7/DAs/CommonDAs/AngleReference.h \
        Part7/DAs/CommonDAs/BSControl.h \
        #Part7/DAs/CommonDAs/Class1.h \
        Part7/DAs/CommonDAs/CMVAngleReference.h \
        Part7/DAs/CommonDAs/ControlOutput.h \
        Part7/DAs/CommonDAs/CtlModels.h \
        Part7/DAs/CommonDAs/CurveChar.h \
        Part7/DAs/CommonDAs/DirectionPhase.h \
        Part7/DAs/CommonDAs/DPStatus.h \
        Part7/DAs/CommonDAs/FaultDirection.h \
        Part7/DAs/CommonDAs/MagReference.h \
        Part7/DAs/CommonDAs/Multiplier.h \
        Part7/DAs/CommonDAs/Originator.h \
        Part7/DAs/CommonDAs/OriginatorCategory.h \
        Part7/DAs/CommonDAs/PhaseReference.h \
        Part7/DAs/CommonDAs/Point.h \
        Part7/DAs/CommonDAs/PointArray.h \
        Part7/DAs/CommonDAs/PulseConfig.h \
        Part7/DAs/CommonDAs/Quality.h \
        Part7/DAs/CommonDAs/Range.h \
        Part7/DAs/CommonDAs/RangeConfig.h \
        Part7/DAs/CommonDAs/SboClasses.h \
        Part7/DAs/CommonDAs/ScaledValueConfig.h \
        Part7/DAs/CommonDAs/Sequence.h \
        Part7/DAs/CommonDAs/Severity.h \
        Part7/DAs/CommonDAs/SIUnits.h \
        Part7/DAs/CommonDAs/Unit.h \
        Part7/DAs/CommonDAs/ValWithTrans.h \
        Part7/DAs/CommonDAs/Vector.h \
        Part7/DAs/CommonDAs/VectorArray.h \
        Part7/LogicalNodes/DomainLNs/DomainLN/DomainLN.h \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ANCR.h \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ARCO.h \
        Part7/LogicalNodes/DomainLNs/LNGroupA/ATCC.h \
        Part7/LogicalNodes/DomainLNs/LNGroupA/GroupA.h \
        Part7/LogicalNodes/DomainLNs/LNGroupF/FSPT.h \
        Part7/LogicalNodes/DomainLNs/LNGroupF/GroupF.h \
        #Part7/LogicalNodes/DomainLNs/LNGroupM/Class1.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/GroupM.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MDIF.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MHAI.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MHAN.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMTR.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMXN.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MMXU.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MSQI.h \
        Part7/LogicalNodes/DomainLNs/LNGroupM/MSTA.h \
        Part7/LogicalNodes/DomainLNs/LNGroupT/GroupT.h \
        Part7/LogicalNodes/DomainLNs/LNGroupT/TCTR.h \
        Part7/LogicalNodes/DomainLNs/LNGroupT/TVTR.h \
        #Part7/LogicalNodes/DomainLNs/LNGroupX/Class1.h \
        Part7/LogicalNodes/DomainLNs/LNGroupX/GroupX.h \
        Part7/LogicalNodes/DomainLNs/LNGroupX/XCBR.h \
        Part7/LogicalNodes/DomainLNs/LNGroupX/XSWI.h \
        Part7/LogicalNodes/DomainLNs/LNGroupY/GroupY.h \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YEFN.h \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YLTC.h \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YPSH.h \
        Part7/LogicalNodes/DomainLNs/LNGroupY/YPTR.h \
        Part7/LogicalNodes/LNGroupL/LLN0.h \
        Part7/LogicalNodes/LNGroupL/LPHD.h

unix {
    target.path   = /usr/lib/IEC61850

    INSTALLS      += target

    headers.path  = /usr/include/IEC61850
    headers.files += $$HEADERS
    INSTALLS      += headers
}
macx {
    target.path   = /usr/lib/IEC61850

    INSTALLS      += target

    headers.path  = /usr/include/IEC61850
    headers.files += $$HEADERS
    INSTALLS      += headers
}

